### ISSUE TITLE
File input for Diffdomain

### ISSUE THREAD

**Issue by FlavianR** [Tian-Dechao/diffDomain#10]
Hi! Thanks for this tool!
I have a question about the format of input file. 
Only file.hic are accepted ? Or can we use an other format (like cool or mcool) with a trick ? 
If not are you planning to add more format possibilities or to stay with only the hic format ?

Thank you in advance for your answers.

**Comment by mingbao96** [comment]
Hi, thank you for your interest in DiffDomain! 
We have updated DiffDomain to directly support input Hi-C data in `.cool` and `.mcool` file formats in addition to `.hic`. You can now use these formats for input as well. For details, please see our [description of Hi-C data ](https://github.com/Tian-Dechao/diffDomain/wiki/2.-Input-format)

To use the updated DiffDomain code, please either download the updated `diffdomain-py3` folder [[link]](https://github.com/Tian-Dechao/diffDomain/tree/main/diffdomain-py3) from GitHub or update to the latest version (0.2.1) using `pip install diffDomain-py3==0.2.1` to access this new feature.

Let me know if you have any more questions or encounter any issues. Thanks again for using DiffDomain!

**Comment by FlavianR** [comment]
Thanks for this update!
