### ISSUE TITLE
Use of precaculated TAD_list

### ISSUE THREAD

**Issue by FlavianR** [Tian-Dechao/diffDomain#12]
Hello again! 
I have questions about the use ofTAD_list generated before the use of DiffDomain.
I don't really understand your documentation on that. You wrote on the main method : 

```
python diffdomains.py dvsd multiple <hic0> <hic1> <tadlist_of_hic0.bed> [options] 
```

Questions :
1- can we put a <tadlist_of_hic1.bed> with it ? or it's just for hic0 ?
2- can you give an exemple of usable <tadlist_of_hic0.bed> ? 
3- if we can't used <tadlist_of_hic1.bed>, how can we compare 2 samples hic with a TAD_list for each ?

Thank you in advance for your answers.

**Comment by Tian-Dechao** [comment]
Thanks for the interests again. 

1. Yes, TADs in Hi-C 2  <tadlist_of_hic1.bed> can be used. 
2.  TADs format is the same as the TADs identified by ArrowHead. See our description of TADs format [here](https://github.com/Tian-Dechao/diffDomain/wiki/2.-Input-format#tads-list). Two example TAD lists in Rao et al  2014, one for GM12878 and the other for IMR90 are also provided at the `/data` folder. 
3. Based on the response to question 1, yes, we can compare 2 samples hic with a TAD_list for each. To do so, run DiffDomain  two times. First time uses hic0 as condition 1, 
`python diffdomains.py dvsd multiple <hic0> <hic1> <tadlist_of_hic0.bed> [options] `
Second time uses  hic1 as condition 1,
`python diffdomains.py dvsd multiple <hic1> <hic0> <tadlist_of_hic1.bed> [options] `

**Comment by FlavianR** [comment]
Ok thanks for the precisions

**Comment by tan5251** [comment]
Hello. which results should be used when we run DiffDomain two times ?

**Comment by Tian-Dechao** [comment]
> Hello. which results should be used when we run DiffDomain two times ?

Depending on the context. Specifically, 
1) if you are interested in the condition 1 TADs that are reorganized in condition 2, using the results from 
`python diffdomains.py dvsd multiple <hic0> <hic1> <tadlist_of_hic0.bed> [options]`
2) if you are interested in the condition 2 TADs that are reorganized in condition 1, using the results from 
`python diffdomains.py dvsd multiple <hic1> <hic0> <tadlist_of_hic1.bed> [options]`

**Comment by tan5251** [comment]
Got it. Thanks for your quick reply. You really made a fast and easy-to-use software！
