### ISSUE TITLE
Question about dvsd multiple output

### ISSUE THREAD

**Issue by yusrepo** [Tian-Dechao/diffDomain#15]
<img width="593" alt="Screenshot 2024-01-25 at 12 12 16 PM" src="https://github.com/Tian-Dechao/diffDomain/assets/139503556/a511e58e-b000-4203-a037-03725248a2b1">

I attached a screenshot of the "dvsd multiple" output file, and I can see the first 4 columns are TAD information I provided as input, and the 6th column is the p-value as mentioned in the wiki. Could you explain what do the 5th column and 7th column mean? 

Also, I provided 2127 TAD entries in the input file, why the output table only gives information of 1885 of them? 

Thank you!

**Comment by Tian-Dechao** [comment]
1 5th column: test statistic 
2 7th column: number of bins, i.e, TAD length / resolution 
3 Some TADs are filtered out, for example, TADs with less than 10 bins, or TADs with high proportion of missing values.

**Comment by yusrepo** [comment]
Thank you for the quick response!
