### ISSUE TITLE
Migrate to Python 3?

### ISSUE THREAD

**Issue by zqzneptune** [Tian-Dechao/diffDomain#3]
Hello, 

Is there any plan to upgrade to Python 3.X, as some dependencies failed to install due to the lack of support for Python 2.7?
e.g. h5py==2.9,

# [What’s new in h5py 2.9](https://docs.h5py.org/en/stable/whatsnew/2.9.html) #
## Support for old Python ##
Support for Python 3.3 has been dropped.
Support for Python 2.6 has been dropped.

**Comment by Tian-Dechao** [comment]
Hey, 

Thank you for the interest. Yes. Python 3 version is on the way. Please wait for a few days.

**Comment by zqzneptune** [comment]
Will wait for your update then, thanks!

**Comment by mingbao96** [comment]
@zqzneptune Hi，Python 3 version has been released on github and Pypi, you can try it by `pip install diffDomain-py3`
