### ISSUE TITLE
DiffDomain v0.0.8 crashing with ImportError.

### ISSUE THREAD

**Issue by tolender** [Tian-Dechao/diffDomain#4]
Hi,
I saw your updated DiffDomain for python3. https://pypi.org/project/DiffDomain/0.0.8/
I successfully install it on python 3.9.12 as well as all of the dependencies.
However, when I run the command below, the program crashes immediately with the trace-back below. 
I look forward to using this program as the paper is very promising!

`python /home/#########/software/diffDomain_v0.0.8/lib/python3.9/site-packages/diffdomain/diffdomains.py dvsd multiple
 Control.hic Treatment.hic Control.bed --hicnorm KR --reso 10000 --oprefix=Control.vs.Treatment

Traceback (most recent call last):
    File "/home/#########/software/diffDomain_v0.0.8/lib/python3.9/site-packages/diffdomain/diffdomains.py", line 31, in <module>
            from .utils import comp2domins_by_twtest, loadtads, visualization
ImportError: attempted relative import with no known parent package`

**Comment by mingbao96** [comment]
The new version has been released, please try it by `pip install diffDomain-py3`
If you encounter any other questions, please contact us

**Comment by tolender** [comment]
_pip install diffDomain-py3_ installed properly and am testing, thank you for the quick response!
