### ISSUE TITLE
1 not found in the file using 'dvsd multiple'

### ISSUE THREAD

**Issue by tolender** [Tian-Dechao/diffDomain#5]
diffDomain is working for "dvsd one", however I am unable to get "dvsd multiple" to work with 2 hic files and a bed file.

Using the code below, I get "1 not found in the file." repeated for the total number of TADs in the bed file, then the program hangs indefinitely.
If the chr column is populated with "chr1", I get the message below.
If the chr column is populated with "1", I get the message below.
If I explicitly add _--chrn "1"_ to the command, I get the message below.
If I explicitly add _--chrn "chr1"_  to the command, the program immediately finishes and the output file only has the # commented rows. 

_python /home/########/diffDomainENV/diffDomain/diffdomain-py3/diffdomains.py dvsd multiple Control.hic Treatment.hic Control_TADs_chr1.txt --ofile Ctrl.vs.Treatment.at.Ctrl_chr1.txt --hicnorm KR --ncore 1 --reso 10000 --min_nbin 5
diffdomains.py
1 not found in the file.
1 not found in the file.
1 not found in the file.
1 not found in the file.
etc 
etc 
etc._

**Comment by mingbao96** [comment]
Have you tested the two hic files in 'dvsd one' on chr1, just like below?
`python diffdomains.py dvsd one 1 1000000 1700000 Control.hic --reso 50000`
`python diffdomains.py dvsd one 1 1000000 1700000 Treatment.hic --reso 50000`

If you can run them and get results from the two files on chr1 using 'dvsd one' respectively, there may be some neglected errors in our scripts. If not, that means hic-straw can not find the 1st chromosome in the hic files.

Actually, in our scripts, if we find 'chr1'  in your tadlist, we will set it as '1', and hic-straw can match chromosome name automatically.


In addition, maybe we should confirm the format of tadlist. We expect a tadlist like below, whose first column is chromosome name, second column is the locus where the TAD starts, and third column is the locus where the TAD ends. We will only use the first 3 columns in a tadlist (framed in red). And whatever its column names are, it should have a header (framed in green).
<img width="704" alt="image" src="https://user-images.githubusercontent.com/35926661/207230885-e9ff05cc-df3b-494d-a9e0-9b7400e53d6d.png">

**Comment by tolender** [comment]
Your suggestion produces an error as inputting a single HIC outputs the Usage.

Here are two regions that I know are the same and different between control and treatment.
 
This is a TAD that does not change at all when viewed on Juicebox

_$ python /project/###########/PythonEnv/diffDomainENV/diffDomain/diffdomain-py3/diffdomains.py dvsd one chr1 69220001 69830000 Control.hic Treatment.hic --hicnorm SCALE --ofile Test1.txt --ncore 1 --reso 10000
diffdomains.py
                           0
0                       chr1
1                   69220001
2                   69830000
3  chrchr1:69220001-69830000
4                   3.566469
5                    0.00055
6                         61_

Here is a TAD that clearly changes when viewed on Juicebox.

_$ python /project/###########/PythonEnv/diffDomainENV/diffDomain/diffdomain-py3/diffdomains.py dvsd one chr14 24950000 25580000 Control.hic Treatment.hic --hicnorm SCALE --ofile Test2.txt --ncore 1 --reso 10000
diffdomains.py
                            0
0                       chr14
1                    24950000
2                    25580000
3  chrchr14:24950000-25580000
4                    6.293985
5                    0.000001
6                          63_

What is notable is 'chrchr' being written in row 3 in both cases, and the region that definitely does not change still has a p-value of 0.00055. The output txt file also writes out the files vertically and not as a tab separate row.

Additionally,
Adding the header "chr1   x1   x2" to the top of the bed file makes no difference to the output of the initial issue.

Which .hic version should be used with for diffDomain? I believe the latest .hic is v9 and my .hic files may be a few versions behind. https://github.com/aidenlab/hictools

Many thanks!

**Comment by mingbao96** [comment]
About the initial problem, based on the information you provided, I guess the issue is hic-straw can not match the chromosome names correctly. When you use 'dvsd one', hic-straw will directly find the chromosome matched with 'chr14'. But when you use 'dvsd multiple', after loading tadlist, hic-straw will try to find the chromosome matched with '14'. 

I think we should adjust the function for loading tadlist. I have updated the package and you can set the chromosome names like 'chr1' and then try 'dvsd multiple' again.

**Comment by mingbao96** [comment]
Regarding the picked TAD chr1:69220001-69830000,  it is likely a false positive based on your description. 
In general, DiffDomain controls FPR when simultaneously comparing multiple TADs. We recommend trying the "dvsd multiple" to test TADs from all chromosomes.

**Comment by mingbao96** [comment]
About the output format of 'dvsd one', the result of 'dvsd one' indeed was written as one column. I have adjusted it to keep the same with 'dvsd multiple'.

**Comment by mingbao96** [comment]
About adding a header to tadlist, yes, it can only avoid omitting the first TAD we want to test.

In addition, to our best knowledge, hic version is not an issue.

**Comment by tolender** [comment]
I appreciate your rapid fixes to the program! I updated to diffDomain_py3_0.1.3
 
The output for "dvsd one" still works correctly and indeed outputs in row format now, thanks for that.

I am getting a new error regarding syntax.

_python /home/######/software/anaconda3/lib/python3.9/site-packages/diffdomain_py3/diffdomains.py dvsd multiple CONTROL.hic TREATMENT.hic CONTROL_chr1.txt --hicnorm SCALE --ofile Test3.txt --ncore 1 --reso 10000  
   File "/home/######/software/anaconda3/lib/python3.9/site-packages/diffdomain_py3/diffdomains.py", line 67
    P = Pool(int(opts['--ncore']))
    ^
SyntaxError: invalid syntax_

**Comment by mingbao96** [comment]
I met this error in my local test and  fixed it. The newest version is 0.1.5, you can reinstall and try it.😄

**Comment by mingbao96** [comment]
The factor is the sequencing coverage. When sequencing coverage is low but a high resolution, say 1 kb, is chosen, the Hi-C contact matrix of a TAD has a high percentage of missing values. So we set a filtering parameter using ‘--f’ to remove Hi-C contact matrices with high percentages of missing values.

  For example, when setting ‘--f 0.6’, if the number of the columns, whose proportions of missing values is higher than 40%, is smaller than min_nbin in a contact matrix of a TAD, DiffDomain will skip comparing this TAD anymore and set its result (statistics, the 5th column ; P value, the 6th column) as NAN.

**Comment by tolender** [comment]
I see, I will close this issue as we are getting off topic, but is it recommended to stay with the default '--f=0.5' only at the default resolution of 100kb? Should it be changed if the resolution is decreased or is that not recommended? 
ex. can the --f be reduced to 0.3 or 0.2 at 5/10/25kb, or will that start introducing uncertainty in the matrix algorithm due to sparsity? 

Thank you again for being so fast in the migration to py3 and updating the code so quickly! It is greatly appreciated!

**Comment by 7insong** [comment]
Chromosome name mismatch occurs in dvsd multiple mode when using BED files with "chr" prefixes (e.g., chr1). The loadtads() function in utils.py fails to process these names because the chromosome format conversion code ”# format the chromosomal names \if 'chr' in tadb.iloc[0,0]: \tadb[0] = tadb[0].str.replace('chr', '')“ is commented out. Uncommenting these lines resolves the issue by removing "chr" prefixes to match .hic file's chromosome format. Suggest enabling this conversion by default or adding a parameter (like --keep-chr-prefix) for flexibility. Tested with diffDomain-py3==0.2.2 (installed via pip install diffDomain-py3==0.2.2 --no-deps) where .hic files use "1"-style naming and BED uses "chr1".
